/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { GetApiGroupEventId200InviteesItemPerson } from "./getApiGroupEventId200InviteesItemPerson";
import type { GetApiGroupEventId200InviteesItemPossibleOptionsItem } from "./getApiGroupEventId200InviteesItemPossibleOptionsItem";

export type GetApiGroupEventId200InviteesItem = {
  /** Identifier of the related group event */
  groupEventId: string;
  /** Identifier of the invitee */
  id: string;
  person: GetApiGroupEventId200InviteesItemPerson;
  /** Identifier of the person invited */
  personId: string;
  /** Array of IDs for the possible options for this invitee */
  possibleOptionIds: string[];
  possibleOptions: GetApiGroupEventId200InviteesItemPossibleOptionsItem[];
};
