/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { Status } from "./status";

export interface GroupEventOptionStatusCreate {
  /** Identifier of the status option */
  id?: string;
  /** Identifier of the group event option */
  optionId: string;
  status: Status;
}
