/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { Invitee } from "./invitee";
import type { Option } from "./option";
import type { Person } from "./person";

export interface GroupEvent {
  /** Unique identifier of the group event */
  id: string;
  invitees: Invitee[];
  options: Option[];
  owner: Person;
}
