/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { GroupEventInviteesItem } from "./groupEventInviteesItem";
import type { GroupEventOption } from "./groupEventOption";
import type { GroupEventOwner } from "./groupEventOwner";

export interface GroupEvent {
  /** Unique identifier of the group event */
  id: string;
  invitees: GroupEventInviteesItem[];
  owner: GroupEventOwner;
  /** Identifier of the owner of the group event */
  ownerId: string;
  suggestedOptions: GroupEventOption[];
}
