/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */

export interface GroupEventOption {
  /** Suggested date for the event */
  date: string;
  /** Identifier of the related group event */
  eventId: string;
  /** Unique identifier of the group event option */
  id: string;
  optionStatusIds: string[];
}
