/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */

/**
 * The owner of the event
 */
export interface GroupEventOptionCreate {
  /** Suggested date for the event */
  date: string;
  /** Unique identifier of the group event option */
  id?: string;
}
