/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { GroupEventOptionStatus } from "./groupEventOptionStatus";
import type { Person } from "./person";

export interface GroupEventInvitee {
  /** Identifier of the related group event */
  groupEventId: string;
  /** Identifier of the invitee */
  id: string;
  optionStatuses: GroupEventOptionStatus[];
  person: Person;
  /** Identifier of the person invited */
  personId: string;
}
