/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { PostApiGroupEventIdJoinBodyPerson } from "./postApiGroupEventIdJoinBodyPerson";

export type PostApiGroupEventIdJoinBody = {
  /** The person joining the event */
  person: PostApiGroupEventIdJoinBodyPerson;
};
