/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { GroupEventOptionCreate } from "./groupEventOptionCreate";
import type { PersonCreate } from "./personCreate";

export type PostApiGroupEventBody = {
  owner: PersonCreate;
  suggestedOptions: GroupEventOptionCreate[];
};
