/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */

export type PostApiGroupEvent201Owner = {
  /** Name of the owner */
  name: string;
};
