/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */

/**
 * The owner of the event
 */
export type PostApiGroupEventBodyOwner = {
  /** Name of the event owner */
  name: string;
};
