/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { PostApiGroupEvent201Owner } from "./postApiGroupEvent201Owner";
import type { PostApiGroupEvent201SuggestedOptionsItem } from "./postApiGroupEvent201SuggestedOptionsItem";

export type PostApiGroupEvent201 = {
  /** Unique identifier of the group event */
  id: string;
  owner: PostApiGroupEvent201Owner;
  /** Identifier of the owner of the group event */
  ownerId: string;
  suggestedOptions: PostApiGroupEvent201SuggestedOptionsItem[];
};
