/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */

export type PostApiGroupEvent201SuggestedOptionsItem = {
  /** Suggested date for the event */
  date: string;
  /** Unique identifier of the group event option */
  id: string;
};
