/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { PostApiGroupEventBodyOwner } from "./postApiGroupEventBodyOwner";
import type { PostApiGroupEventBodySuggestedOptionsItem } from "./postApiGroupEventBodySuggestedOptionsItem";

export type PostApiGroupEventBody = {
  /** The owner of the event */
  owner: PostApiGroupEventBodyOwner;
  suggestedOptions: PostApiGroupEventBodySuggestedOptionsItem[];
};
