/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */

export type PostApiGroupEventBodySuggestedOptionsItem = {
  /** Suggested date for the event */
  date: string;
};
