/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */

export type PostApiGroupEventIdJoin201 = {
  /** Id of the person who joined */
  id: string;
  /** Name of the person who joined */
  name: string;
};
