/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { PutApiGroupEventId200InviteesItem } from "./putApiGroupEventId200InviteesItem";
import type { PutApiGroupEventId200Owner } from "./putApiGroupEventId200Owner";
import type { PutApiGroupEventId200SuggestedOptionsItem } from "./putApiGroupEventId200SuggestedOptionsItem";

export type PutApiGroupEventId200 = {
  /** Unique identifier of the group event */
  id: string;
  invitees: PutApiGroupEventId200InviteesItem[];
  owner: PutApiGroupEventId200Owner;
  /** Identifier of the owner of the group event */
  ownerId: string;
  suggestedOptions: PutApiGroupEventId200SuggestedOptionsItem[];
};
