/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { PutApiGroupEventIdBodyInviteesItemPerson } from "./putApiGroupEventIdBodyInviteesItemPerson";
import type { PutApiGroupEventIdBodyInviteesItemPossibleOptionsItem } from "./putApiGroupEventIdBodyInviteesItemPossibleOptionsItem";

export type PutApiGroupEventIdBodyInviteesItem = {
  /** Identifier of the related group event */
  groupEventId: string;
  /** Identifier of the invitee */
  id: string;
  person: PutApiGroupEventIdBodyInviteesItemPerson;
  /** Identifier of the person invited */
  personId: string;
  /** Array of IDs for the possible options for this invitee */
  possibleOptionIds: string[];
  possibleOptions: PutApiGroupEventIdBodyInviteesItemPossibleOptionsItem[];
};
