/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { Option } from "./option";

export type PutApiGroupEventIdBody = {
  /** Unique identifier of the group event */
  id: string;
  options: Option[];
};
