/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */

export type PutApiGroupEventIdJoinPersonId201 = {
  /** Identifier of the updated invitee */
  id: string;
  /** Identifier of the person (invitee) */
  personId: string;
  /** Updated array of possible option IDs for the invitee */
  possibleOptionIds: string[];
};
