/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */

export type PutApiGroupEventIdJoinPersonIdBody = {
  /** Array of possible option IDs that the person is interested in */
  possibleOptions: string[];
};
