/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { PutApiGroupEventIdBodyInviteesItem } from "./putApiGroupEventIdBodyInviteesItem";
import type { PutApiGroupEventIdBodyOwner } from "./putApiGroupEventIdBodyOwner";
import type { PutApiGroupEventIdBodySuggestedOptionsItem } from "./putApiGroupEventIdBodySuggestedOptionsItem";

export type PutApiGroupEventIdBody = {
  /** Unique identifier of the group event */
  id: string;
  invitees?: PutApiGroupEventIdBodyInviteesItem[];
  owner?: PutApiGroupEventIdBodyOwner;
  /** Identifier of the owner of the group event */
  ownerId?: string;
  suggestedOptions: PutApiGroupEventIdBodySuggestedOptionsItem[];
};
