/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { GroupEventOptionStatusCreate } from "./groupEventOptionStatusCreate";

export type PutApiGroupEventIdJoinPersonIdBody = {
  optionStatuses: GroupEventOptionStatusCreate[];
};
