/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */

/**
 * Rsvp statuses
 */
export type RSVPResponse = (typeof RSVPResponse)[keyof typeof RSVPResponse];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RSVPResponse = {
  NOT_POSSIBLE: "NOT_POSSIBLE",
  POSSIBLE: "POSSIBLE",
  TENTATIVE: "TENTATIVE",
} as const;
