/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */
import type { RSVPResponse } from "./rSVPResponse";

export interface Rsvp {
  /** Identifier of the group event option */
  date: string;
  response: RSVPResponse;
}
