/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Next Swagger API Example
 * OpenAPI spec version: 1.0
 */

/**
 * Updated status of the invitee for this option
 */
export type Status = (typeof Status)[keyof typeof Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status = {
  Not_voted: "Not voted",
  Not_possible: "Not possible",
  Possible: "Possible",
  Reluctant: "Reluctant",
} as const;
